Repository brain-tec/account-invoicing, pull requests merged in 2019-04, with the labels that each got.

#246 Syncing from upstream OCA/account-invoicing (8.0)
  account_group_invoice_lines/static/description/icon.png
  account_invoice_force_number/static/description/icon.png
  account_invoice_kanban/static/description/icon.png
  account_invoice_line_sort/static/description/icon.png
  account_invoice_merge/static/description/icon.png
  account_invoice_merge_payment/static/description/icon.png
  account_invoice_merge_purchase/static/description/icon.png
  account_invoice_partner/static/description/icon.png
  account_invoice_period_usability/static/description/icon.png
  account_invoice_pricelist/static/description/icon.png
  account_invoice_pricelist_sale/static/description/icon.png
  account_invoice_pricelist_sale_stock/static/description/icon.png
  account_invoice_rounding/static/description/icon.png
  account_invoice_rounding_by_currency/static/description/icon.png
  account_invoice_shipping_address/static/description/icon.png
  account_invoice_supplier_number_info/static/description/icon.png
  account_invoice_supplier_ref_unique/static/description/icon.png
  account_invoice_transmit_method/static/description/icon.png
  account_invoice_triple_discount/static/description/icon.png
  account_invoice_validation_workflow/static/description/icon.png
  account_invoice_zero_autopay/static/description/icon.png
  account_payment_term_extension/static/description/icon.png
  invoice_fiscal_position_update/static/description/icon.png
  invoice_margin/static/description/icon.png
  stock_picking_invoicing_unified/static/description/icon.png
Labels: 8.0

#247 Syncing from upstream OCA/account-invoicing (9.0)
  account_invoice_line_sequence/static/description/icon.png
  account_invoice_merge/static/description/icon.png
  account_invoice_merge_payment/static/description/icon.png
  account_invoice_merge_purchase/static/description/icon.png
  account_invoice_pricelist/static/description/icon.png
  account_invoice_rounding/static/description/icon.png
  account_invoice_search_by_reference/static/description/icon.png
  account_invoice_supplier_ref_unique/static/description/icon.png
  sale_timesheet_invoice_description/static/description/icon.png
Labels: 9.0

#248 Syncing from upstream OCA/account-invoicing (10.0)
  account_group_invoice_line/static/description/icon.png
  account_invoice_change_currency/static/description/icon.png
  account_invoice_fiscal_position_update/static/description/icon.png
  account_invoice_kanban/static/description/icon.png
  account_invoice_line_sequence/static/description/icon.png
  account_invoice_merge_payment/static/description/icon.png
  account_invoice_merge_purchase/static/description/icon.png
  account_invoice_partner/static/description/icon.png
  account_invoice_pricelist/static/description/icon.png
  account_invoice_pricelist_sale/static/description/icon.png
  account_invoice_pro_forma_sequence/static/description/icon.png
  account_invoice_rounding/static/description/icon.png
  account_invoice_search_by_reference/static/description/icon.png
  account_invoice_supplier_ref_unique/static/description/icon.png
  account_invoice_transmit_method/static/description/icon.png
  account_invoice_triple_discount/static/description/icon.png
  product_supplierinfo_for_customer_invoice/static/description/icon.png
  sale_timesheet_invoice_description/static/description/icon.png
Labels: 10.0

#249 Syncing from upstream OCA/account-invoicing (11.0)
  account_invoice_anglo_saxon_no_cogs_deferral/static/description/icon.png
  account_invoice_change_currency/static/description/icon.png
  account_invoice_fiscal_position_update/static/description/icon.png
  account_invoice_pricelist/static/description/icon.png
  account_invoice_supplier_ref_reuse/static/description/icon.png
  account_invoice_supplier_ref_unique/static/description/icon.png
  account_invoice_tax_note/static/description/icon.png
  account_invoice_triple_discount/static/description/icon.png
  sale_timesheet_invoice_description/static/description/icon.png
Labels: 11.0

#250 Syncing from upstream OCA/account-invoicing (12.0)
  account_invoice_change_currency/static/description/icon.png
  account_invoice_fiscal_position_update/static/description/icon.png
  account_invoice_pricelist/static/description/icon.png
  account_invoice_search_by_reference/static/description/icon.png
  account_invoice_triple_discount/static/description/icon.png
  sale_timesheet_invoice_description/static/description/icon.png
Labels: 12.0

#251 Syncing from upstream OCA/account-invoicing (11.0)
  account_invoice_refund_line_selection/README.rst
  account_invoice_refund_line_selection/__init__.py
  account_invoice_refund_line_selection/__manifest__.py
  account_invoice_refund_line_selection/i18n/account_invoice_refund_line_selection.pot
  account_invoice_refund_line_selection/models/__init__.py
  account_invoice_refund_line_selection/models/account_invoice.py
  account_invoice_refund_line_selection/static/description/icon.png
  account_invoice_refund_line_selection/tests/__init__.py
  account_invoice_refund_line_selection/tests/test_refund_line.py
  account_invoice_refund_line_selection/wizards/__init__.py
  account_invoice_refund_line_selection/wizards/account_invoice_refund.py
  account_invoice_refund_line_selection/wizards/account_invoice_refund_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_refund_line_selection/odoo/addons/account_invoice_refund_line_selection
  setup/account_invoice_refund_line_selection/setup.cfg
  setup/account_invoice_refund_line_selection/setup.py
Labels: 11.0

#252 [t114208] added account_invoice_fixed_discount module from v11
  account_invoice_fixed_discount/README.rst
  account_invoice_fixed_discount/__init__.py
  account_invoice_fixed_discount/__manifest__.py
  account_invoice_fixed_discount/i18n/account_invoice_fixed_discount.pot
  account_invoice_fixed_discount/models/__init__.py
  account_invoice_fixed_discount/models/account_invoice.py
  account_invoice_fixed_discount/readme/CONTRIBUTORS.rst
  account_invoice_fixed_discount/readme/DESCRIPTION.rst
  account_invoice_fixed_discount/readme/INSTALL.rst
  account_invoice_fixed_discount/readme/ROADMAP.rst
  account_invoice_fixed_discount/readme/USAGE.rst
  account_invoice_fixed_discount/reports/report_account_invoice.xml
  account_invoice_fixed_discount/static/description/icon.png
  account_invoice_fixed_discount/static/description/index.html
  account_invoice_fixed_discount/tests/__init__.py
  account_invoice_fixed_discount/tests/test_account_fixed_discount.py
  account_invoice_fixed_discount/views/account_invoice_view.xml
Labels: 12.0.project_mi_465

#253 Syncing from upstream OCA/account-invoicing (11.0)
  account_invoice_refund_line_selection/i18n/es.po
Labels: 11.0
