Repository brain-tec/account-invoicing, pull requests merged in 2022-08, with the labels that each got.

#739 Syncing from upstream OCA/account-invoicing (12.0)
  account_menu_invoice_refund/i18n/it.po
Labels: 12.0

#740 [t130438][15.0][MIG] account_invoice_validation_queued
  account_invoice_validation_queued/README.rst
  account_invoice_validation_queued/__init__.py
  account_invoice_validation_queued/__manifest__.py
  account_invoice_validation_queued/data/queue_job.xml
  account_invoice_validation_queued/i18n/account_invoice_validation_queued.pot
  account_invoice_validation_queued/i18n/ca.po
  account_invoice_validation_queued/i18n/es.po
  account_invoice_validation_queued/models/__init__.py
  account_invoice_validation_queued/models/account_move.py
  account_invoice_validation_queued/readme/CONFIGURE.rst
  account_invoice_validation_queued/readme/CONTRIBUTORS.rst
  account_invoice_validation_queued/readme/DESCRIPTION.rst
  account_invoice_validation_queued/readme/INSTALL.rst
  account_invoice_validation_queued/readme/ROADMAP.rst
  account_invoice_validation_queued/readme/USAGE.rst
  account_invoice_validation_queued/static/description/icon.png
  account_invoice_validation_queued/static/description/index.html
  account_invoice_validation_queued/tests/__init__.py
  account_invoice_validation_queued/tests/test_account_invoice_validation_queued.py
  account_invoice_validation_queued/views/account_invoice_views.xml
  account_invoice_validation_queued/views/queue_job_views.xml
  account_invoice_validation_queued/wizards/__init__.py
  account_invoice_validation_queued/wizards/validate_account_move.py
  account_invoice_validation_queued/wizards/validate_account_move_view.xml
  setup/account_invoice_validation_queued/setup.py
Labels: odoo_migration, 15.0.project_pn15

#741 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_move_exception/README.rst
  account_move_exception/__init__.py
  account_move_exception/__manifest__.py
  account_move_exception/data/account_exception_data.xml
  account_move_exception/i18n/account_move_exception.pot
  account_move_exception/i18n/ca.po
  account_move_exception/init_hook.py
  account_move_exception/models/__init__.py
  account_move_exception/models/account_move.py
  account_move_exception/models/account_move_line.py
  account_move_exception/models/exception_rule.py
  account_move_exception/readme/CONTRIBUTORS.rst
  account_move_exception/readme/DESCRIPTION.rst
  account_move_exception/readme/USAGE.rst
  account_move_exception/security/ir.model.access.csv
  account_move_exception/static/description/icon.png
  account_move_exception/static/description/index.html
  account_move_exception/tests/__init__.py
  account_move_exception/tests/test_account_exception.py
  account_move_exception/views/account_view.xml
  account_move_exception/wizard/__init__.py
  account_move_exception/wizard/account_exception_confirm.py
  account_move_exception/wizard/account_exception_confirm_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_exception/odoo/addons/account_move_exception
  setup/account_move_exception/setup.py
Labels: 15.0

#742 Syncing from upstream OCA/account-invoicing (13.0)
  README.md
  account_invoice_origin_link/README.rst
  account_invoice_origin_link/__init__.py
  account_invoice_origin_link/__manifest__.py
  account_invoice_origin_link/i18n/account_invoice_origin_link.pot
  account_invoice_origin_link/models/__init__.py
  account_invoice_origin_link/models/account_move.py
  account_invoice_origin_link/readme/CONTRIBUTORS.rst
  account_invoice_origin_link/readme/DESCRIPTION.rst
  account_invoice_origin_link/static/description/icon.png
  account_invoice_origin_link/static/description/index.html
  account_invoice_origin_link/views/account_move_views.xml
  account_invoice_sale_origin_link/README.rst
  account_invoice_sale_origin_link/__init__.py
  account_invoice_sale_origin_link/__manifest__.py
  account_invoice_sale_origin_link/i18n/account_invoice_sale_origin_link.pot
  account_invoice_sale_origin_link/models/__init__.py
  account_invoice_sale_origin_link/models/account_move.py
  account_invoice_sale_origin_link/readme/CONTRIBUTORS.rst
  account_invoice_sale_origin_link/readme/DESCRIPTION.rst
  account_invoice_sale_origin_link/static/description/icon.png
  account_invoice_sale_origin_link/static/description/index.html
  account_invoice_sale_origin_link/tests/__init__.py
  account_invoice_sale_origin_link/tests/test_account_invoice_sale_origin_link.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/views/account_move_view.xml
  account_move_tier_validation_forward/README.rst
  account_move_tier_validation_forward/__init__.py
  account_move_tier_validation_forward/__manifest__.py
  account_move_tier_validation_forward/i18n/account_move_tier_validation_forward.pot
  account_move_tier_validation_forward/readme/CONFIGURE.rst
  account_move_tier_validation_forward/readme/CONTRIBUTORS.rst
  account_move_tier_validation_forward/readme/DESCRIPTION.rst
  account_move_tier_validation_forward/readme/INSTALL.rst
  account_move_tier_validation_forward/static/description/icon.png
  account_move_tier_validation_forward/static/description/index.html
  account_move_tier_validation_forward/views/account_move_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_origin_link/odoo/addons/account_invoice_origin_link
  setup/account_invoice_origin_link/setup.py
  setup/account_invoice_sale_origin_link/odoo/addons/account_invoice_sale_origin_link
  setup/account_invoice_sale_origin_link/setup.py
  setup/account_move_tier_validation_forward/odoo/addons/account_move_tier_validation_forward
  setup/account_move_tier_validation_forward/setup.py
Labels: 13.0

#743 Syncing from upstream OCA/account-invoicing (14.0)
  account_invoice_pricelist/i18n/ca.po
Labels: 14.0

#744 Syncing from upstream OCA/account-invoicing (15.0)
  account_invoice_change_currency/i18n/ca.po
  account_invoice_date_due/i18n/ca.po
  account_invoice_tax_note/i18n/ca.po
  account_invoice_tax_required/i18n/ca.po
  account_invoice_tree_currency/i18n/ca.po
  account_invoice_triple_discount/i18n/ca.po
  sale_order_invoicing_grouping_criteria/i18n/ca.po
  stock_picking_return_refund_option/i18n/ca.po
Labels: 15.0

#745 Syncing from upstream OCA/account-invoicing (12.0)
  README.md
  account_invoice_confirm_popup/README.rst
  account_invoice_confirm_popup/__init__.py
  account_invoice_confirm_popup/__manifest__.py
  account_invoice_confirm_popup/i18n/account_invoice_confirm_popup.pot
  account_invoice_confirm_popup/i18n/fr.po
  account_invoice_confirm_popup/readme/CONFIGURE.rst
  account_invoice_confirm_popup/readme/CONTRIBUTORS.rst
  account_invoice_confirm_popup/readme/DESCRIPTION.rst
  account_invoice_confirm_popup/static/description/icon.png
  account_invoice_confirm_popup/static/description/index.html
  account_invoice_confirm_popup/views/account_invoice_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_confirm_popup/odoo/addons/account_invoice_confirm_popup
  setup/account_invoice_confirm_popup/setup.py
Labels: 12.0

#746 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_invoice_pricelist_sale/README.rst
  account_invoice_pricelist_sale/__init__.py
  account_invoice_pricelist_sale/__manifest__.py
  account_invoice_pricelist_sale/i18n/account_invoice_pricelist_sale.pot
  account_invoice_pricelist_sale/i18n/ca.po
  account_invoice_pricelist_sale/i18n/de.po
  account_invoice_pricelist_sale/i18n/el_GR.po
  account_invoice_pricelist_sale/i18n/es.po
  account_invoice_pricelist_sale/i18n/es_ES.po
  account_invoice_pricelist_sale/i18n/es_VE.po
  account_invoice_pricelist_sale/i18n/fi.po
  account_invoice_pricelist_sale/i18n/fr.po
  account_invoice_pricelist_sale/i18n/hr.po
  account_invoice_pricelist_sale/i18n/hr_HR.po
  account_invoice_pricelist_sale/i18n/hu.po
  account_invoice_pricelist_sale/i18n/it.po
  account_invoice_pricelist_sale/i18n/nl.po
  account_invoice_pricelist_sale/i18n/nl_NL.po
  account_invoice_pricelist_sale/i18n/pt.po
  account_invoice_pricelist_sale/i18n/pt_BR.po
  account_invoice_pricelist_sale/i18n/ro.po
  account_invoice_pricelist_sale/i18n/sl.po
  account_invoice_pricelist_sale/i18n/tr.po
  account_invoice_pricelist_sale/i18n/tr_TR.po
  account_invoice_pricelist_sale/i18n/vi_VN.po
  account_invoice_pricelist_sale/i18n/zh_CN.po
  account_invoice_pricelist_sale/models/__init__.py
  account_invoice_pricelist_sale/models/sale_order.py
  account_invoice_pricelist_sale/readme/CONTRIBUTORS.rst
  account_invoice_pricelist_sale/readme/DESCRIPTION.rst
  account_invoice_pricelist_sale/readme/INSTALLATION.rst
  account_invoice_pricelist_sale/static/description/icon.png
  account_invoice_pricelist_sale/static/description/index.html
  account_invoice_pricelist_sale/tests/__init__.py
  account_invoice_pricelist_sale/tests/test_module.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/ca.po
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/es_PA.po
  account_move_tier_validation/i18n/sv.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/views/account_move_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_pricelist_sale/odoo/addons/account_invoice_pricelist_sale
  setup/account_invoice_pricelist_sale/setup.py
Labels: 14.0

#748 Syncing from upstream OCA/account-invoicing (12.0)
  account_invoice_tier_validation/i18n/pt_BR.po
  stock_picking_invoicing/i18n/pt_BR.po
Labels: 12.0

#749 Syncing from upstream OCA/account-invoicing (14.0)
  account_invoice_pricelist_sale/i18n/ca.po
  account_invoice_pricelist_sale/i18n/de.po
  account_invoice_pricelist_sale/i18n/el_GR.po
  stock_picking_invoicing/i18n/pt_BR.po
Labels: 14.0

#750 Syncing from upstream OCA/account-invoicing (14.0)
  account_global_discount/i18n/pt.po
Labels: 14.0

#751 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_tax_group_widget_base_amount/README.rst
  account_tax_group_widget_base_amount/__init__.py
  account_tax_group_widget_base_amount/__manifest__.py
  account_tax_group_widget_base_amount/i18n/account_tax_group_widget_base_amount.pot
  account_tax_group_widget_base_amount/i18n/es.po
  account_tax_group_widget_base_amount/readme/CONTRIBUTORS.rst
  account_tax_group_widget_base_amount/readme/DESCRIPTION.rst
  account_tax_group_widget_base_amount/static/description/account_tax_group_widget_base_amount.png
  account_tax_group_widget_base_amount/static/description/icon.png
  account_tax_group_widget_base_amount/static/description/index.html
  account_tax_group_widget_base_amount/static/src/xml/tax_group.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_tax_group_widget_base_amount/odoo/addons/account_tax_group_widget_base_amount
  setup/account_tax_group_widget_base_amount/setup.py
Labels: 15.0

#754 Syncing from upstream OCA/account-invoicing (13.0)
  README.md
  account_invoice_refund_link/__manifest__.py
  account_invoice_refund_link/models/account_move.py
Labels: 13.0

#755 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_invoice_refund_link/__manifest__.py
  account_invoice_refund_link/models/account_move.py
  account_invoice_supplierinfo_update/i18n/es_AR.po
Labels: 14.0

#757 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_invoice_supplierinfo_update_discount/README.rst
  account_invoice_supplierinfo_update_discount/__init__.py
  account_invoice_supplierinfo_update_discount/__manifest__.py
  account_invoice_supplierinfo_update_discount/i18n/account_invoice_supplierinfo_update_discount.pot
  account_invoice_supplierinfo_update_discount/i18n/ar.po
  account_invoice_supplierinfo_update_discount/i18n/bs.po
  account_invoice_supplierinfo_update_discount/i18n/ca.po
  account_invoice_supplierinfo_update_discount/i18n/cs.po
  account_invoice_supplierinfo_update_discount/i18n/de.po
  account_invoice_supplierinfo_update_discount/i18n/en_GB.po
  account_invoice_supplierinfo_update_discount/i18n/es.po
  account_invoice_supplierinfo_update_discount/i18n/es_CR.po
  account_invoice_supplierinfo_update_discount/i18n/es_EC.po
  account_invoice_supplierinfo_update_discount/i18n/es_MX.po
  account_invoice_supplierinfo_update_discount/i18n/et.po
  account_invoice_supplierinfo_update_discount/i18n/fr.po
  account_invoice_supplierinfo_update_discount/i18n/fr_CH.po
  account_invoice_supplierinfo_update_discount/i18n/hr.po
  account_invoice_supplierinfo_update_discount/i18n/hu.po
  account_invoice_supplierinfo_update_discount/i18n/it.po
  account_invoice_supplierinfo_update_discount/i18n/ja.po
  account_invoice_supplierinfo_update_discount/i18n/lt.po
  account_invoice_supplierinfo_update_discount/i18n/mk.po
  account_invoice_supplierinfo_update_discount/i18n/mn.po
  account_invoice_supplierinfo_update_discount/i18n/nb.po
  account_invoice_supplierinfo_update_discount/i18n/nl.po
  account_invoice_supplierinfo_update_discount/i18n/nl_BE.po
  account_invoice_supplierinfo_update_discount/i18n/nl_NL.po
  account_invoice_supplierinfo_update_discount/i18n/pt.po
  account_invoice_supplierinfo_update_discount/i18n/pt_BR.po
  account_invoice_supplierinfo_update_discount/i18n/pt_PT.po
  account_invoice_supplierinfo_update_discount/i18n/ro.po
  account_invoice_supplierinfo_update_discount/i18n/ru.po
  account_invoice_supplierinfo_update_discount/i18n/sl.po
  account_invoice_supplierinfo_update_discount/i18n/sv.po
  account_invoice_supplierinfo_update_discount/i18n/tr.po
  account_invoice_supplierinfo_update_discount/i18n/tr_TR.po
  account_invoice_supplierinfo_update_discount/i18n/zh_CN.po
  account_invoice_supplierinfo_update_discount/i18n/zh_TW.po
  account_invoice_supplierinfo_update_discount/models/__init__.py
  account_invoice_supplierinfo_update_discount/models/account_move_line.py
  account_invoice_supplierinfo_update_discount/readme/CONTRIBUTORS.rst
  account_invoice_supplierinfo_update_discount/readme/DESCRIPTION.rst
  account_invoice_supplierinfo_update_discount/readme/ROADMAP.rst
  account_invoice_supplierinfo_update_discount/static/description/icon.png
  account_invoice_supplierinfo_update_discount/static/description/index.html
  account_invoice_supplierinfo_update_discount/tests/__init__.py
  account_invoice_supplierinfo_update_discount/tests/test_account_invoice_supplierinfo_update_discount.py
  account_invoice_supplierinfo_update_discount/wizard/__init__.py
  account_invoice_supplierinfo_update_discount/wizard/wizard_update_invoice_supplierinfo.xml
  account_invoice_supplierinfo_update_discount/wizard/wizard_update_invoice_supplierinfo_line.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_supplierinfo_update_discount/odoo/addons/account_invoice_supplierinfo_update_discount
  setup/account_invoice_supplierinfo_update_discount/setup.py
Labels: 14.0
