Repository brain-tec/account-invoicing, pull requests merged in 2023-07, with the labels that each got.

#1004 Syncing from upstream OCA/account-invoicing (16.0)
  account_invoice_blocking/i18n/pt_BR.po
  account_invoice_check_total/i18n/pt_BR.po
  account_invoice_fiscal_position_update/i18n/pt_BR.po
  account_invoice_merge/i18n/pt_BR.po
  account_invoice_pricelist_sale/i18n/pt_BR.po
  account_invoice_transmit_method/i18n/pt_BR.po
  account_invoice_triple_discount/i18n/pt_BR.po
  purchase_stock_picking_return_invoicing/i18n/pt_BR.po
Labels: 16.0

#1005 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/ca.po
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/es_PA.po
  account_move_tier_validation/i18n/sv.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/readme/CONFIGURE.rst
  account_move_tier_validation/readme/CONTRIBUTORS.rst
  account_move_tier_validation/readme/DESCRIPTION.rst
  account_move_tier_validation/readme/INSTALL.rst
  account_move_tier_validation/readme/USAGE.rst
  account_move_tier_validation/static/description/icon.png
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/views/account_move_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_tier_validation/odoo/addons/account_move_tier_validation
  setup/account_move_tier_validation/setup.py
Labels: 16.0

#1006 16.0 mig account invoice refund reason
  account_invoice_refund_reason/README.rst
  account_invoice_refund_reason/__init__.py
  account_invoice_refund_reason/__manifest__.py
  account_invoice_refund_reason/data/account.move.refund.reason.csv
  account_invoice_refund_reason/i18n/account_invoice_refund_reason.pot
  account_invoice_refund_reason/i18n/de.po
  account_invoice_refund_reason/i18n/es.po
  account_invoice_refund_reason/i18n/hr.po
  account_invoice_refund_reason/migrations/14.0.1.0.0/pre-migration.py
  account_invoice_refund_reason/models/__init__.py
  account_invoice_refund_reason/models/account_move.py
  account_invoice_refund_reason/models/account_move_refund_reason.py
  account_invoice_refund_reason/readme/CONFIGURE.rst
  account_invoice_refund_reason/readme/CONTRIBUTORS.rst
  account_invoice_refund_reason/readme/DESCRIPTION.rst
  account_invoice_refund_reason/readme/USAGE.rst
  account_invoice_refund_reason/security/ir.model.access.csv
  account_invoice_refund_reason/static/description/icon.png
  account_invoice_refund_reason/static/description/index.html
  account_invoice_refund_reason/tests/__init__.py
  account_invoice_refund_reason/tests/test_account_invoice_refund_reason.py
  account_invoice_refund_reason/views/account_move_refund_reason_view.xml
  account_invoice_refund_reason/views/account_move_view.xml
  account_invoice_refund_reason/wizard/__init__.py
  account_invoice_refund_reason/wizard/account_move_reversal.py
  account_invoice_refund_reason/wizard/account_move_reversal_view.xml
  setup/account_invoice_refund_reason/odoo/addons/account_invoice_refund_reason
  setup/account_invoice_refund_reason/setup.py
Labels: 16.0.project_gv_545

#1007 [t137088] Fixes to the account_invoice_refund_reason
  account_invoice_refund_reason/tests/test_account_invoice_refund_reason.py
  account_invoice_refund_reason/wizard/account_move_reversal.py
Labels: 16.0.project_gv_545

#1008 [bt#23172] Fix bug where some discounts weren't reset
  account_invoice_triple_discount/models/account_move_line.py
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
Labels: 15.0.project_pr_606

#1009 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_tax_group_widget_base_amount/README.rst
  account_tax_group_widget_base_amount/__init__.py
  account_tax_group_widget_base_amount/__manifest__.py
  account_tax_group_widget_base_amount/i18n/account_tax_group_widget_base_amount.pot
  account_tax_group_widget_base_amount/i18n/es.po
  account_tax_group_widget_base_amount/readme/CONTRIBUTORS.rst
  account_tax_group_widget_base_amount/readme/DESCRIPTION.rst
  account_tax_group_widget_base_amount/static/description/account_tax_group_widget_base_amount.png
  account_tax_group_widget_base_amount/static/description/icon.png
  account_tax_group_widget_base_amount/static/description/index.html
  account_tax_group_widget_base_amount/static/src/xml/tax_group.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_tax_group_widget_base_amount/odoo/addons/account_tax_group_widget_base_amount
  setup/account_tax_group_widget_base_amount/setup.py
Labels: 16.0

#1010 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_invoice_refund_line_selection/README.rst
  account_invoice_refund_line_selection/__init__.py
  account_invoice_refund_line_selection/__manifest__.py
  account_invoice_refund_line_selection/i18n/account_invoice_refund_line_selection.pot
  account_invoice_refund_line_selection/i18n/ca.po
  account_invoice_refund_line_selection/i18n/de.po
  account_invoice_refund_line_selection/i18n/es.po
  account_invoice_refund_line_selection/i18n/nl.po
  account_invoice_refund_line_selection/readme/CONTRIBUTORS.rst
  account_invoice_refund_line_selection/readme/DESCRIPTION.rst
  account_invoice_refund_line_selection/readme/USAGE.rst
  account_invoice_refund_line_selection/static/description/icon.png
  account_invoice_refund_line_selection/static/description/index.html
  account_invoice_refund_line_selection/tests/__init__.py
  account_invoice_refund_line_selection/tests/test_refund_line.py
  account_invoice_refund_line_selection/wizards/__init__.py
  account_invoice_refund_line_selection/wizards/account_move_reversal.py
  account_invoice_refund_line_selection/wizards/account_move_reversal_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_refund_line_selection/odoo/addons/account_invoice_refund_line_selection
  setup/account_invoice_refund_line_selection/setup.py
Labels: 15.0

#1011 Syncing from upstream OCA/account-invoicing (9.0)
  sale_stock_picking_return_invoicing/i18n/it.po
  sale_timesheet_invoice_description/i18n/it.po
Labels: 9.0

#1012 Syncing from upstream OCA/account-invoicing (10.0)
  sale_timesheet_invoice_description/i18n/it.po
Labels: 10.0

#1013 Syncing from upstream OCA/account-invoicing (11.0)
  sale_timesheet_invoice_description/i18n/it.po
Labels: 11.0

#1014 Syncing from upstream OCA/account-invoicing (10.0)
  account_group_invoice_line/i18n/es.po
Labels: 10.0

#1015 Syncing from upstream OCA/account-invoicing (12.0)
  account_group_invoice_line/i18n/es.po
Labels: 12.0

#1016 Syncing from upstream OCA/account-invoicing (14.0)
  account_invoice_base_invoicing_mode/i18n/es.po
  account_invoice_mode_monthly/i18n/es.po
  account_invoice_mode_weekly/i18n/es.po
Labels: 14.0

#1017 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_invoice_crm_tag/README.rst
  account_invoice_crm_tag/__init__.py
  account_invoice_crm_tag/__manifest__.py
  account_invoice_crm_tag/i18n/account_invoice_crm_tag.pot
  account_invoice_crm_tag/i18n/es.po
  account_invoice_crm_tag/models/__init__.py
  account_invoice_crm_tag/models/account_move.py
  account_invoice_crm_tag/models/sale_order.py
  account_invoice_crm_tag/readme/CONTRIBUTORS.rst
  account_invoice_crm_tag/readme/DESCRIPTION.rst
  account_invoice_crm_tag/readme/USAGE.rst
  account_invoice_crm_tag/report/__init__.py
  account_invoice_crm_tag/report/account_invoice_report.py
  account_invoice_crm_tag/report/account_invoice_report.xml
  account_invoice_crm_tag/static/description/icon.png
  account_invoice_crm_tag/static/description/index.html
  account_invoice_crm_tag/views/account_invoice_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_crm_tag/odoo/addons/account_invoice_crm_tag
  setup/account_invoice_crm_tag/setup.py
Labels: 15.0

#1018 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_invoice_crm_tag/__manifest__.py
  account_invoice_crm_tag/models/sale_order.py
Labels: 15.0

#1019 Syncing from upstream OCA/account-invoicing (16.0)
  account_receipt_journal/i18n/es.po
  account_receipt_send/i18n/es.po
  account_tax_change/i18n/es.po
  partner_invoicing_mode/i18n/es.po
  partner_invoicing_mode_at_shipping/i18n/es.po
Labels: 16.0

#1020 Syncing from upstream OCA/account-invoicing (15.0)
  account_global_discount/i18n/es.po
  account_invoice_blocking/i18n/es.po
  account_invoice_change_currency/i18n/es.po
  account_invoice_clearing/i18n/es.po
  stock_picking_invoicing_incoterm/i18n/es.po
Labels: 15.0

#1021 Syncing from upstream OCA/account-invoicing (16.0)
  account_invoice_blocking/i18n/es.po
  account_invoice_triple_discount/i18n/es.po
  account_move_tier_validation/i18n/es.po
  account_receipt_journal/i18n/es.po
  account_receipt_send/i18n/es.po
  account_tax_change/i18n/es.po
  partner_invoicing_mode/i18n/es.po
  partner_invoicing_mode_at_shipping/i18n/es.po
  partner_invoicing_mode_monthly/i18n/es.po
  purchase_stock_picking_return_invoicing/i18n/es.po
Labels: 16.0
