Repository brain-tec/account-invoicing, pull requests merged in 2023-11, with the labels that each got.

#1096 Syncing from upstream OCA/account-invoicing (12.0)
  account_invoice_supplierinfo_update/i18n/it.po
Labels: 12.0

#1097 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_invoice_supplier_ref_unique/i18n/es.po
  account_invoice_warn_message/README.rst
  account_invoice_warn_message/__init__.py
  account_invoice_warn_message/__manifest__.py
  account_invoice_warn_message/i18n/account_invoice_warn_message.pot
  account_invoice_warn_message/i18n/es.po
  account_invoice_warn_message/models/__init__.py
  account_invoice_warn_message/models/account_move.py
  account_invoice_warn_message/readme/CONTRIBUTORS.rst
  account_invoice_warn_message/readme/DESCRIPTION.rst
  account_invoice_warn_message/static/description/icon.png
  account_invoice_warn_message/static/description/index.html
  account_invoice_warn_message/tests/__init__.py
  account_invoice_warn_message/tests/test_account_invoice_warn_message.py
  account_invoice_warn_message/views/account_move_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_warn_message/odoo/addons/account_invoice_warn_message
  setup/account_invoice_warn_message/setup.py
Labels: 15.0

#1098 Syncing from upstream OCA/account-invoicing (15.0)
  account_invoice_warn_message/i18n/es.po
  account_move_post_block/i18n/es.po
Labels: 15.0

#1099 Syncing from upstream OCA/account-invoicing (12.0)
  README.md
  account_invoice_supplierinfo_update/README.rst
  account_invoice_supplierinfo_update/__manifest__.py
  account_invoice_supplierinfo_update/i18n/it.po
  account_invoice_supplierinfo_update/static/description/index.html
  account_invoice_supplierinfo_update/tests/test_account_invoice_supplierinfo_update.py
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo_line.py
Labels: 12.0

#1100 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_invoice_supplierinfo_update/README.rst
  account_invoice_supplierinfo_update/__manifest__.py
  account_invoice_supplierinfo_update/static/description/index.html
  account_invoice_supplierinfo_update/tests/test_account_invoice_supplierinfo_update.py
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo_line.py
Labels: 14.0

#1101 Syncing from upstream OCA/account-invoicing (16.0)
  sale_timesheet_invoice_description/i18n/it.po
Labels: 16.0

#1102 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_invoice_payment_retention/README.rst
  account_invoice_payment_retention/__init__.py
  account_invoice_payment_retention/__manifest__.py
  account_invoice_payment_retention/i18n/account_invoice_payment_retention.pot
  account_invoice_payment_retention/i18n/ca.po
  account_invoice_payment_retention/models/__init__.py
  account_invoice_payment_retention/models/account_move.py
  account_invoice_payment_retention/models/res_company.py
  account_invoice_payment_retention/models/res_config_settings.py
  account_invoice_payment_retention/readme/CONFIGURE.rst
  account_invoice_payment_retention/readme/CONTRIBUTORS.rst
  account_invoice_payment_retention/readme/DESCRIPTION.rst
  account_invoice_payment_retention/readme/USAGE.rst
  account_invoice_payment_retention/security/security.xml
  account_invoice_payment_retention/static/description/icon.png
  account_invoice_payment_retention/static/description/index.html
  account_invoice_payment_retention/tests/__init__.py
  account_invoice_payment_retention/tests/test_invoice_payment_retention.py
  account_invoice_payment_retention/views/account_move_views.xml
  account_invoice_payment_retention/views/res_config_settings_views.xml
  account_invoice_payment_retention/wizard/__init__.py
  account_invoice_payment_retention/wizard/account_payment_register.py
  account_invoice_payment_retention/wizard/account_payment_register_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_payment_retention/odoo/addons/account_invoice_payment_retention
  setup/account_invoice_payment_retention/setup.py
Labels: 15.0

#1104 Syncing from upstream OCA/account-invoicing (12.0)
  account_invoice_supplierinfo_update/i18n/it.po
Labels: 12.0

#1105 Syncing from upstream OCA/account-invoicing (14.0)
  account_invoice_triple_discount/i18n/it.po
Labels: 14.0

#1106 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_tax_one_vat/README.rst
  account_tax_one_vat/__init__.py
  account_tax_one_vat/__manifest__.py
  account_tax_one_vat/i18n/account_tax_one_vat.pot
  account_tax_one_vat/i18n/fr_BE.po
  account_tax_one_vat/models/__init__.py
  account_tax_one_vat/models/account_move.py
  account_tax_one_vat/models/account_move_line.py
  account_tax_one_vat/models/account_tax.py
  account_tax_one_vat/models/account_tax_template.py
  account_tax_one_vat/models/one_vat_mixin.py
  account_tax_one_vat/models/product_template.py
  account_tax_one_vat/models/res_company.py
  account_tax_one_vat/models/res_config_settings.py
  account_tax_one_vat/readme/CONTRIBUTORS.rst
  account_tax_one_vat/readme/DESCRIPTION.rst
  account_tax_one_vat/readme/USAGE.rst
  account_tax_one_vat/static/description/icon.png
  account_tax_one_vat/static/description/index.html
  account_tax_one_vat/tests/__init__.py
  account_tax_one_vat/tests/common.py
  account_tax_one_vat/tests/test_account_tax_one_vat.py
  account_tax_one_vat/views/account_tax_views.xml
  account_tax_one_vat/views/res_config_settings_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_tax_one_vat/odoo/addons/account_tax_one_vat
  setup/account_tax_one_vat/setup.py
Labels: 16.0

#1107 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_global_discount/README.rst
  account_global_discount/__init__.py
  account_global_discount/__manifest__.py
  account_global_discount/hooks.py
  account_global_discount/static/description/index.html
Labels: 14.0

#1108 Syncing from upstream OCA/account-invoicing (14.0)
  account_invoice_date_due/i18n/es.po
Labels: 14.0

#1111 [t143286][FIX] Filter refunds to set the reason.
  account_invoice_refund_reason/wizard/account_move_reversal.py
Labels: 16.0.project_gv_545

#1110 [MIG] account_invoice_payment_term_date_due: Migration to 16.0
  account_invoice_payment_term_date_due/README.rst
  account_invoice_payment_term_date_due/__init__.py
  account_invoice_payment_term_date_due/__manifest__.py
  account_invoice_payment_term_date_due/i18n/account_invoice_payment_term_date_due.pot
  account_invoice_payment_term_date_due/readme/CONTRIBUTORS.rst
  account_invoice_payment_term_date_due/readme/DESCRIPTION.rst
  account_invoice_payment_term_date_due/static/description/account-invoice-payment-term-due-date.png
  account_invoice_payment_term_date_due/static/description/icon.png
  account_invoice_payment_term_date_due/static/description/index.html
  account_invoice_payment_term_date_due/views/account_move.xml
  setup/account_invoice_payment_term_date_due/odoo/addons/account_invoice_payment_term_date_due
  setup/account_invoice_payment_term_date_due/setup.py
Labels: 16.0.project_gv_545

#1112 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_invoice_refund_link/README.rst
  account_invoice_refund_link/__manifest__.py
  account_invoice_refund_link/static/description/index.html
  account_invoice_refund_link/tests/test_invoice_refund_link.py
Labels: 14.0

#1113 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_invoice_base_invoicing_mode/README.rst
  account_invoice_base_invoicing_mode/__manifest__.py
  account_invoice_base_invoicing_mode/models/sale_order.py
  account_invoice_base_invoicing_mode/readme/CONTRIBUTORS.rst
  account_invoice_base_invoicing_mode/static/description/index.html
  account_invoice_base_invoicing_mode/tests/__init__.py
  account_invoice_base_invoicing_mode/tests/common.py
  account_invoice_base_invoicing_mode/tests/test_invoice_base_mode.py
  account_invoice_mode_at_shipping/README.rst
  account_invoice_mode_at_shipping/__manifest__.py
  account_invoice_mode_at_shipping/models/stock_picking.py
  account_invoice_mode_at_shipping/readme/CONTRIBUTORS.rst
  account_invoice_mode_at_shipping/static/description/index.html
  account_invoice_mode_at_shipping/tests/test_invoice_mode_at_shipping.py
  account_invoice_mode_monthly/README.rst
  account_invoice_mode_monthly/__init__.py
  account_invoice_mode_monthly/__manifest__.py
  account_invoice_mode_monthly/models/sale_order.py
  account_invoice_mode_monthly/readme/CONTRIBUTORS.rst
  account_invoice_mode_monthly/static/description/index.html
  account_invoice_mode_monthly/tests/test_invoice_mode_monthly.py
  account_invoice_mode_weekly/README.rst
  account_invoice_mode_weekly/__init__.py
  account_invoice_mode_weekly/__manifest__.py
  account_invoice_mode_weekly/models/sale_order.py
  account_invoice_mode_weekly/readme/CONTRIBUTORS.rst
  account_invoice_mode_weekly/static/description/index.html
  account_invoice_mode_weekly/tests/test_invoice_mode_weekly.py
  account_invoice_pricelist/README.rst
  account_invoice_pricelist/__manifest__.py
  account_invoice_pricelist/readme/CONTRIBUTORS.rst
  account_invoice_pricelist/static/description/index.html
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: 14.0

#1114 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_invoice_triple_discount/README.rst
  account_invoice_triple_discount/__manifest__.py
  account_invoice_triple_discount/models/account_move.py
  account_invoice_triple_discount/static/description/index.html
Labels: 14.0

#1115 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_triple_discount/README.rst
  account_invoice_triple_discount/__manifest__.py
  account_invoice_triple_discount/models/account_move.py
  account_invoice_triple_discount/models/account_move_line.py
  account_invoice_triple_discount/readme/CONTRIBUTORS.rst
  account_invoice_triple_discount/static/description/index.html
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
Labels: 16.0

#1118 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_manual_currency/README.rst
  account_manual_currency/__init__.py
  account_manual_currency/__manifest__.py
  account_manual_currency/data/decimal_data.xml
  account_manual_currency/i18n/account_manual_currency.pot
  account_manual_currency/models/__init__.py
  account_manual_currency/models/account_move.py
  account_manual_currency/readme/CONTRIBUTORS.rst
  account_manual_currency/readme/DESCRIPTION.rst
  account_manual_currency/readme/USAGE.rst
  account_manual_currency/static/description/icon.png
  account_manual_currency/static/description/index.html
  account_manual_currency/tests/__init__.py
  account_manual_currency/tests/test_account_manual_currency.py
  account_manual_currency/views/account_move_view.xml
  account_manual_currency/wizard/__init__.py
  account_manual_currency/wizard/account_payment_register.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_manual_currency/odoo/addons/account_manual_currency
  setup/account_manual_currency/setup.py
Labels: 15.0

#1119 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_invoicing/odoo/addons/stock_picking_invoicing
  setup/stock_picking_invoicing/setup.py
  stock_picking_invoicing/README.rst
  stock_picking_invoicing/__init__.py
  stock_picking_invoicing/__manifest__.py
  stock_picking_invoicing/demo/stock_picking_demo.xml
  stock_picking_invoicing/i18n/ca.po
  stock_picking_invoicing/i18n/de.po
  stock_picking_invoicing/i18n/es.po
  stock_picking_invoicing/i18n/fr.po
  stock_picking_invoicing/i18n/pt_BR.po
  stock_picking_invoicing/i18n/sl.po
  stock_picking_invoicing/i18n/stock_picking_invoicing.pot
  stock_picking_invoicing/models/__init__.py
  stock_picking_invoicing/models/account_move.py
  stock_picking_invoicing/models/stock_invoice_state_mixin.py
  stock_picking_invoicing/models/stock_move.py
  stock_picking_invoicing/models/stock_picking.py
  stock_picking_invoicing/models/stock_picking_type.py
  stock_picking_invoicing/readme/CONTRIBUTORS.rst
  stock_picking_invoicing/readme/DESCRIPTION.rst
  stock_picking_invoicing/readme/HISTORY.rst
  stock_picking_invoicing/readme/INSTALL.rst
  stock_picking_invoicing/readme/USAGE.rst
  stock_picking_invoicing/security/ir.model.access.csv
  stock_picking_invoicing/static/description/icon.png
  stock_picking_invoicing/static/description/index.html
  stock_picking_invoicing/tests/__init__.py
  stock_picking_invoicing/tests/common.py
  stock_picking_invoicing/tests/test_picking_invoicing.py
  stock_picking_invoicing/views/stock_move_views.xml
  stock_picking_invoicing/views/stock_picking_type_views.xml
  stock_picking_invoicing/views/stock_picking_views.xml
  stock_picking_invoicing/wizards/__init__.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping_view.xml
  stock_picking_invoicing/wizards/stock_return_picking.py
  stock_picking_invoicing/wizards/stock_return_picking_view.xml
Labels: 16.0

#1120 Syncing from upstream OCA/account-invoicing (14.0)
  sale_timesheet_invoice_description/i18n/it.po
Labels: 14.0

#1121 Syncing from upstream OCA/account-invoicing (16.0)
  account_invoice_refund_code/i18n/es.po
  account_tax_one_vat/i18n/es.po
  stock_picking_invoicing/i18n/es.po
Labels: 16.0
