Repository brain-tec/account-invoicing, pull requests merged in 2023-05, with the labels that each got.

#942 Syncing from upstream OCA/account-invoicing (13.0)
  account_billing/i18n/nl_NL.po
Labels: 13.0

#943 Syncing from upstream OCA/account-invoicing (14.0)
  account_billing/i18n/nl_NL.po
Labels: 14.0

#941 [bt#22420] Avoid side effects when resetting discounts
  account_invoice_triple_discount/models/account_move_line.py
Labels: 15.0.project_pr_606

#944 Syncing from upstream OCA/account-invoicing (10.0)
  product_supplierinfo_for_customer_invoice/i18n/it.po
Labels: 10.0

#945 Syncing from upstream OCA/account-invoicing (11.0)
  product_supplierinfo_for_customer_invoice/i18n/it.po
Labels: 11.0

#946 Syncing from upstream OCA/account-invoicing (12.0)
  account_invoice_supplierinfo_update/i18n/it.po
  product_supplierinfo_for_customer_invoice/i18n/it.po
Labels: 12.0

#947 Syncing from upstream OCA/account-invoicing (13.0)
  product_supplierinfo_for_customer_invoice/i18n/it.po
Labels: 13.0

#948 Syncing from upstream OCA/account-invoicing (14.0)
  product_supplierinfo_for_customer_invoice/i18n/it.po
Labels: 14.0

#949 Syncing from upstream OCA/account-invoicing (15.0)
  product_supplierinfo_for_customer_invoice/i18n/it.po
Labels: 15.0

#950 Syncing from upstream OCA/account-invoicing (9.0)
  account_invoice_merge/i18n/it.po
Labels: 9.0

#951 Syncing from upstream OCA/account-invoicing (10.0)
  account_invoice_merge/i18n/it.po
  account_invoice_supplierinfo_update/i18n/it.po
  account_invoice_transmit_method/i18n/it.po
  account_payment_term_extension/i18n/it.po
Labels: 10.0

#952 Syncing from upstream OCA/account-invoicing (12.0)
  account_global_discount/i18n/it.po
  sale_timesheet_invoice_description/i18n/it.po
Labels: 12.0

#953 Syncing from upstream OCA/account-invoicing (14.0)
  account_global_discount/i18n/it.po
  sale_timesheet_invoice_description/i18n/it.po
Labels: 14.0

#954 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_global_discount/i18n/it.po
  sale_timesheet_invoice_description/__manifest__.py
  sale_timesheet_invoice_description/i18n/it.po
  sale_timesheet_invoice_description/tests/test_sale_timesheet_description.py
Labels: 15.0

#955 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_merge/__manifest__.py
  account_invoice_merge/models/account_move.py
  account_invoice_merge/tests/test_account_invoice_merge.py
Labels: 16.0

#958 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_tax_change/README.rst
  account_tax_change/__init__.py
  account_tax_change/__manifest__.py
  account_tax_change/i18n/account_tax_change.pot
  account_tax_change/models/__init__.py
  account_tax_change/models/account_tax_change.py
  account_tax_change/readme/CONFIGURE.rst
  account_tax_change/readme/CONTRIBUTORS.rst
  account_tax_change/readme/DESCRIPTION.rst
  account_tax_change/readme/USAGE.rst
  account_tax_change/security/ir.model.access.csv
  account_tax_change/static/description/account_tax_change.png
  account_tax_change/static/description/apply_tax_changes_form.png
  account_tax_change/static/description/apply_tax_changes_menu.png
  account_tax_change/static/description/icon.png
  account_tax_change/static/description/index.html
  account_tax_change/tests/__init__.py
  account_tax_change/tests/common.py
  account_tax_change/tests/test_account_tax_change.py
  account_tax_change/views/account_tax_change.xml
  account_tax_change/wizards/__init__.py
  account_tax_change/wizards/account_move_apply_tax_change.py
  account_tax_change/wizards/account_move_apply_tax_change.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_tax_change/odoo/addons/account_tax_change
  setup/account_tax_change/setup.py
Labels: 16.0

#959 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_invoice_pricelist/__manifest__.py
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: 15.0

#960 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_invoicing/odoo/addons/stock_picking_invoicing
  setup/stock_picking_invoicing/setup.py
  stock_picking_invoicing/README.rst
  stock_picking_invoicing/__init__.py
  stock_picking_invoicing/__manifest__.py
  stock_picking_invoicing/demo/stock_picking_demo.xml
  stock_picking_invoicing/i18n/ca.po
  stock_picking_invoicing/i18n/de.po
  stock_picking_invoicing/i18n/es.po
  stock_picking_invoicing/i18n/fr.po
  stock_picking_invoicing/i18n/pt_BR.po
  stock_picking_invoicing/i18n/sl.po
  stock_picking_invoicing/i18n/stock_picking_invoicing.pot
  stock_picking_invoicing/models/__init__.py
  stock_picking_invoicing/models/account_move.py
  stock_picking_invoicing/models/stock_invoice_state_mixin.py
  stock_picking_invoicing/models/stock_move.py
  stock_picking_invoicing/models/stock_picking.py
  stock_picking_invoicing/models/stock_picking_type.py
  stock_picking_invoicing/readme/CONTRIBUTORS.rst
  stock_picking_invoicing/readme/DESCRIPTION.rst
  stock_picking_invoicing/readme/HISTORY.rst
  stock_picking_invoicing/readme/INSTALL.rst
  stock_picking_invoicing/readme/USAGE.rst
  stock_picking_invoicing/security/ir.model.access.csv
  stock_picking_invoicing/static/description/icon.png
  stock_picking_invoicing/static/description/index.html
  stock_picking_invoicing/tests/__init__.py
  stock_picking_invoicing/tests/test_picking_invoicing.py
  stock_picking_invoicing/views/stock_move.xml
  stock_picking_invoicing/views/stock_picking.xml
  stock_picking_invoicing/views/stock_picking_type.xml
  stock_picking_invoicing/wizards/__init__.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping_view.xml
  stock_picking_invoicing/wizards/stock_return_picking.py
  stock_picking_invoicing/wizards/stock_return_picking_view.xml
Labels: 15.0

#961 Syncing from upstream OCA/account-invoicing (8.0)
  account_invoice_supplierinfo_update/i18n/it.po
Labels: 8.0

#962 Syncing from upstream OCA/account-invoicing (9.0)
  purchase_batch_invoicing/i18n/it.po
Labels: 9.0

#963 Syncing from upstream OCA/account-invoicing (10.0)
  account_invoice_merge/i18n/it.po
  account_invoice_supplierinfo_update/i18n/it.po
Labels: 10.0

#964 Syncing from upstream OCA/account-invoicing (11.0)
  purchase_batch_invoicing/i18n/it.po
Labels: 11.0

#965 Syncing from upstream OCA/account-invoicing (12.0)
  account_invoice_supplierinfo_update/i18n/it.po
Labels: 12.0

#966 Syncing from upstream OCA/account-invoicing (15.0)
  account_invoice_merge/i18n/it.po
Labels: 15.0

#967 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_invoice_clearing/README.rst
  account_invoice_clearing/__init__.py
  account_invoice_clearing/__manifest__.py
  account_invoice_clearing/i18n/account_invoice_clearing.pot
  account_invoice_clearing/i18n/es.po
  account_invoice_clearing/models/__init__.py
  account_invoice_clearing/models/account_move.py
  account_invoice_clearing/readme/CONTRIBUTORS.rst
  account_invoice_clearing/readme/CREDITS.rst
  account_invoice_clearing/readme/DESCRIPTION.rst
  account_invoice_clearing/readme/ROADMAP.rst
  account_invoice_clearing/readme/USAGE.rst
  account_invoice_clearing/security/ir.model.access.csv
  account_invoice_clearing/static/description/icon.png
  account_invoice_clearing/static/description/index.html
  account_invoice_clearing/tests/__init__.py
  account_invoice_clearing/tests/test_clearing_wizard.py
  account_invoice_clearing/views/account_move_view.xml
  account_invoice_clearing/wizards/__init__.py
  account_invoice_clearing/wizards/account_invoice_clearing_wizard.py
  account_invoice_clearing/wizards/account_invoice_clearing_wizard_views.xml
  account_invoice_merge/i18n/it.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_clearing/odoo/addons/account_invoice_clearing
  setup/account_invoice_clearing/setup.py
Labels: 15.0

#968 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_receipt_journal/README.rst
  account_receipt_journal/__init__.py
  account_receipt_journal/__manifest__.py
  account_receipt_journal/data/account_journal_data.xml
  account_receipt_journal/i18n/account_receipt_journal.pot
  account_receipt_journal/models/__init__.py
  account_receipt_journal/models/account_journal.py
  account_receipt_journal/models/account_move.py
  account_receipt_journal/readme/CONTRIBUTORS.rst
  account_receipt_journal/readme/DESCRIPTION.rst
  account_receipt_journal/readme/HISTORY.rst
  account_receipt_journal/static/description/icon.png
  account_receipt_journal/static/description/index.html
  account_receipt_journal/tests/__init__.py
  account_receipt_journal/tests/test_receipts.py
  account_receipt_journal/views/account_journal_views.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_receipt_journal/odoo/addons/account_receipt_journal
  setup/account_receipt_journal/setup.py
Labels: 16.0

#969 Syncing from upstream OCA/account-invoicing (8.0)
  account_invoice_kanban/i18n/it.po
  account_invoice_merge/i18n/it.po
  account_invoice_supplierinfo_update/i18n/it.po
  account_invoice_transmit_method/i18n/it.po
Labels: 8.0

#970 Syncing from upstream OCA/account-invoicing (12.0)
  README.md
  account_portal_invoice_search/README.rst
  account_portal_invoice_search/__init__.py
  account_portal_invoice_search/__manifest__.py
  account_portal_invoice_search/controllers/__init__.py
  account_portal_invoice_search/controllers/portal.py
  account_portal_invoice_search/models/__init__.py
  account_portal_invoice_search/models/account_move.py
  account_portal_invoice_search/readme/CONTRIBUTORS.rst
  account_portal_invoice_search/readme/DESCRIPTION.rst
  account_portal_invoice_search/readme/USAGE.rst
  account_portal_invoice_search/static/description/icon.png
  account_portal_invoice_search/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_portal_invoice_search/odoo/addons/account_portal_invoice_search
  setup/account_portal_invoice_search/setup.py
Labels: 12.0

#971 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_change_currency/README.rst
  account_invoice_change_currency/__init__.py
  account_invoice_change_currency/__manifest__.py
  account_invoice_change_currency/hooks.py
  account_invoice_change_currency/i18n/account_invoice_change_currency.pot
  account_invoice_change_currency/i18n/ca.po
  account_invoice_change_currency/i18n/de.po
  account_invoice_change_currency/i18n/es.po
  account_invoice_change_currency/i18n/es_MX.po
  account_invoice_change_currency/i18n/hr.po
  account_invoice_change_currency/models/__init__.py
  account_invoice_change_currency/models/account_move.py
  account_invoice_change_currency/models/account_move_line.py
  account_invoice_change_currency/models/res_currency.py
  account_invoice_change_currency/readme/CONFIGURE.rst
  account_invoice_change_currency/readme/CONTRIBUTORS.rst
  account_invoice_change_currency/readme/DESCRIPTION.rst
  account_invoice_change_currency/readme/USAGE.rst
  account_invoice_change_currency/static/description/icon.png
  account_invoice_change_currency/static/description/index.html
  account_invoice_change_currency/tests/__init__.py
  account_invoice_change_currency/tests/test_account_invoice_change_currency.py
  account_invoice_change_currency/views/account_move_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_change_currency/odoo/addons/account_invoice_change_currency
  setup/account_invoice_change_currency/setup.py
Labels: 16.0

#972 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_invoice_payment_retention/models/res_config_settings.py
  account_move_post_block/i18n/account_move_post_block.pot
  account_move_post_block/i18n/fi.po
  account_move_post_block/views/account_post_block_reason_view.xml
  account_move_tier_validation_approver/README.rst
  account_move_tier_validation_approver/__init__.py
  account_move_tier_validation_approver/__manifest__.py
  account_move_tier_validation_approver/i18n/account_move_tier_validation_approver.pot
  account_move_tier_validation_approver/i18n/es_PA.po
  account_move_tier_validation_approver/models/__init__.py
  account_move_tier_validation_approver/models/account_move.py
  account_move_tier_validation_approver/models/res_company.py
  account_move_tier_validation_approver/models/res_config_settings.py
  account_move_tier_validation_approver/models/res_partner.py
  account_move_tier_validation_approver/readme/CONFIGURE.rst
  account_move_tier_validation_approver/readme/CONTRIBUTORS.rst
  account_move_tier_validation_approver/readme/DESCRIPTION.rst
  account_move_tier_validation_approver/readme/USAGE.rst
  account_move_tier_validation_approver/static/description/icon.png
  account_move_tier_validation_approver/static/description/index.html
  account_move_tier_validation_approver/tests/__init__.py
  account_move_tier_validation_approver/tests/test_account_move_tier_validation_approver.py
  account_move_tier_validation_approver/views/account_move_views.xml
  account_move_tier_validation_approver/views/res_config_settings_views.xml
  account_move_tier_validation_approver/views/res_partner_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_tier_validation_approver/odoo/addons/account_move_tier_validation_approver
  setup/account_move_tier_validation_approver/setup.py
Labels: 14.0
