Repository brain-tec/account-invoicing, pull requests merged in 2024-11, with the labels that each got.

#1338 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_invoice_view_payment/README.rst
  account_invoice_view_payment/__manifest__.py
  account_invoice_view_payment/models/account_move.py
  account_invoice_view_payment/static/description/index.html
  account_invoice_view_payment/tests/test_account_invoice_view_payment.py
Labels: 15.0

#1339 [17.0][MIG] account_move_tier_validation
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/ca.po
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/es_PA.po
  account_move_tier_validation/i18n/fr.po
  account_move_tier_validation/i18n/hr.po
  account_move_tier_validation/i18n/it.po
  account_move_tier_validation/i18n/sv.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/pyproject.toml
  account_move_tier_validation/readme/CONFIGURE.md
  account_move_tier_validation/readme/CONTRIBUTORS.md
  account_move_tier_validation/readme/DESCRIPTION.md
  account_move_tier_validation/readme/INSTALL.md
  account_move_tier_validation/readme/USAGE.md
  account_move_tier_validation/static/description/icon.png
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/views/account_move_view.xml
Labels: 17.0.project_ev_734

#1340 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_account_move_reset_to_draft/odoo/addons/stock_account_move_reset_to_draft
  setup/stock_account_move_reset_to_draft/setup.py
  stock_account_move_reset_to_draft/README.rst
  stock_account_move_reset_to_draft/__init__.py
  stock_account_move_reset_to_draft/__manifest__.py
  stock_account_move_reset_to_draft/i18n/es.po
  stock_account_move_reset_to_draft/i18n/stock_account_move_reset_to_draft.pot
  stock_account_move_reset_to_draft/models/__init__.py
  stock_account_move_reset_to_draft/models/account_move.py
  stock_account_move_reset_to_draft/readme/CONTEXT.rst
  stock_account_move_reset_to_draft/readme/CONTRIBUTORS.rst
  stock_account_move_reset_to_draft/readme/DESCRIPTION.rst
  stock_account_move_reset_to_draft/readme/USAGE.rst
  stock_account_move_reset_to_draft/static/description/icon.png
  stock_account_move_reset_to_draft/static/description/index.html
  stock_account_move_reset_to_draft/tests/__init__.py
  stock_account_move_reset_to_draft/tests/test_stock_account_move_reset_to_draft.py
Labels: 16.0

#1341 Syncing from upstream OCA/account-invoicing (14.0)
  account_invoice_force_number/i18n/it.po
Labels: 14.0

#1343 Syncing from upstream OCA/account-invoicing (13.0)
  README.md
  account_invoice_show_currency_rate/README.rst
  account_invoice_show_currency_rate/__manifest__.py
  account_invoice_show_currency_rate/models/account_move.py
  account_invoice_show_currency_rate/static/description/index.html
Labels: 13.0

#1344 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_show_currency_rate/README.rst
  account_invoice_show_currency_rate/__manifest__.py
  account_invoice_show_currency_rate/models/account_move.py
  account_invoice_show_currency_rate/static/description/index.html
  stock_account_move_reset_to_draft/i18n/it.po
Labels: 16.0

#1345 Syncing from upstream OCA/account-invoicing (17.0)
  README.md
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/ca.po
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/es_PA.po
  account_move_tier_validation/i18n/fr.po
  account_move_tier_validation/i18n/hr.po
  account_move_tier_validation/i18n/it.po
  account_move_tier_validation/i18n/sv.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/pyproject.toml
  account_move_tier_validation/readme/CONFIGURE.md
  account_move_tier_validation/readme/CONTRIBUTORS.md
  account_move_tier_validation/readme/DESCRIPTION.md
  account_move_tier_validation/readme/INSTALL.md
  account_move_tier_validation/readme/USAGE.md
  account_move_tier_validation/static/description/icon.png
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/views/account_move_view.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1346 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_invoice_auto_send_by_email/README.rst
  account_invoice_auto_send_by_email/__init__.py
  account_invoice_auto_send_by_email/__manifest__.py
  account_invoice_auto_send_by_email/data/ir_cron.xml
  account_invoice_auto_send_by_email/i18n/account_invoice_auto_send_by_email.pot
  account_invoice_auto_send_by_email/models/__init__.py
  account_invoice_auto_send_by_email/models/account_invoice_send.py
  account_invoice_auto_send_by_email/models/account_move.py
  account_invoice_auto_send_by_email/readme/CONTRIBUTORS.rst
  account_invoice_auto_send_by_email/readme/DESCRIPTION.rst
  account_invoice_auto_send_by_email/static/description/icon.png
  account_invoice_auto_send_by_email/static/description/index.html
  account_invoice_auto_send_by_email/tests/__init__.py
  account_invoice_auto_send_by_email/tests/test_account_invoice_auto_send_by_email.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_auto_send_by_email/odoo/addons/account_invoice_auto_send_by_email
  setup/account_invoice_auto_send_by_email/setup.py
Labels: 14.0

#1347 Syncing from upstream OCA/account-invoicing (17.0)
  account_move_tier_validation/i18n/it.po
Labels: 17.0

#1348 Syncing from upstream OCA/account-invoicing (15.0)
  README.md
  account_invoice_mass_sending/README.rst
  account_invoice_mass_sending/__manifest__.py
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/static/description/index.html
  account_invoice_mass_sending/wizards/account_invoice_send.py
Labels: 15.0

#1349 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  stock_account_move_reset_to_draft/README.rst
  stock_account_move_reset_to_draft/__manifest__.py
  stock_account_move_reset_to_draft/readme/CONTEXT.rst
  stock_account_move_reset_to_draft/readme/DESCRIPTION.rst
  stock_account_move_reset_to_draft/readme/USAGE.rst
  stock_account_move_reset_to_draft/static/description/index.html
Labels: 16.0

#1350 Syncing from upstream OCA/account-invoicing (17.0)
  README.md
  portal_account_personal_data_only/README.rst
  portal_account_personal_data_only/__init__.py
  portal_account_personal_data_only/__manifest__.py
  portal_account_personal_data_only/hooks.py
  portal_account_personal_data_only/i18n/es.po
  portal_account_personal_data_only/i18n/it.po
  portal_account_personal_data_only/i18n/portal_account_personal_data_only.pot
  portal_account_personal_data_only/pyproject.toml
  portal_account_personal_data_only/readme/CONTRIBUTORS.md
  portal_account_personal_data_only/readme/DESCRIPTION.md
  portal_account_personal_data_only/readme/USAGE.md
  portal_account_personal_data_only/security/security.xml
  portal_account_personal_data_only/static/description/icon.png
  portal_account_personal_data_only/static/description/index.html
  portal_account_personal_data_only/tests/__init__.py
  portal_account_personal_data_only/tests/test_partner_access.py
  sale_order_invoicing_qty_percentage/README.rst
  sale_order_invoicing_qty_percentage/__init__.py
  sale_order_invoicing_qty_percentage/__manifest__.py
  sale_order_invoicing_qty_percentage/i18n/es.po
  sale_order_invoicing_qty_percentage/i18n/it.po
  sale_order_invoicing_qty_percentage/i18n/sale_order_invoicing_qty_percentage.pot
  sale_order_invoicing_qty_percentage/models/__init__.py
  sale_order_invoicing_qty_percentage/models/sale_order.py
  sale_order_invoicing_qty_percentage/pyproject.toml
  sale_order_invoicing_qty_percentage/readme/CONTRIBUTORS.md
  sale_order_invoicing_qty_percentage/readme/DESCRIPTION.md
  sale_order_invoicing_qty_percentage/readme/ROADMAP.md
  sale_order_invoicing_qty_percentage/readme/USAGE.md
  sale_order_invoicing_qty_percentage/static/description/icon.png
  sale_order_invoicing_qty_percentage/static/description/index.html
  sale_order_invoicing_qty_percentage/tests/__init__.py
  sale_order_invoicing_qty_percentage/tests/test_sale_order_invoicing_qty_percentage.py
  sale_order_invoicing_qty_percentage/wizards/__init__.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv_views.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1351 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_mass_sending/README.rst
  account_invoice_mass_sending/__manifest__.py
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/static/description/index.html
  account_invoice_mass_sending/wizards/account_invoice_send.py
Labels: 16.0

#1352 Syncing from upstream OCA/account-invoicing (17.0)
  portal_account_personal_data_only/i18n/es.po
  portal_account_personal_data_only/i18n/it.po
Labels: 17.0

#1353 Syncing from upstream OCA/account-invoicing (14.0)
  README.md
  account_invoice_mass_sending/README.rst
  account_invoice_mass_sending/__manifest__.py
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/static/description/index.html
  account_invoice_mass_sending/wizards/account_invoice_send.py
Labels: 14.0

#1354 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  stock_picking_invoicing/README.rst
  stock_picking_invoicing/__manifest__.py
  stock_picking_invoicing/i18n/ca.po
  stock_picking_invoicing/i18n/de.po
  stock_picking_invoicing/i18n/es.po
  stock_picking_invoicing/i18n/fr.po
  stock_picking_invoicing/i18n/hr.po
  stock_picking_invoicing/i18n/it.po
  stock_picking_invoicing/i18n/pt_BR.po
  stock_picking_invoicing/i18n/sl.po
  stock_picking_invoicing/i18n/stock_picking_invoicing.pot
  stock_picking_invoicing/models/__init__.py
  stock_picking_invoicing/models/stock_rule.py
  stock_picking_invoicing/static/description/index.html
Labels: 16.0

#1355 Syncing from upstream OCA/account-invoicing (16.0)
  stock_picking_invoicing/i18n/it.po
Labels: 16.0

#1356 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_pricelist/README.rst
  account_invoice_pricelist/__manifest__.py
  account_invoice_pricelist/models/account_move.py
  account_invoice_pricelist/static/description/index.html
Labels: 16.0

#1357 Syncing from upstream OCA/account-invoicing (17.0)
  README.md
  account_invoice_pricelist/README.rst
  account_invoice_pricelist/__manifest__.py
  account_invoice_pricelist/models/account_move.py
  account_invoice_pricelist/static/description/index.html
Labels: 17.0
