Repository brain-tec/account-invoicing, pull requests merged in 2024-06, with the labels that each got.

#1253 [t148475] Merging open migration PR for: account_move_tier_validation
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/ca.po
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/es_PA.po
  account_move_tier_validation/i18n/sv.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/pyproject.toml
  account_move_tier_validation/readme/CONFIGURE.md
  account_move_tier_validation/readme/CONTRIBUTORS.md
  account_move_tier_validation/readme/DESCRIPTION.md
  account_move_tier_validation/readme/INSTALL.md
  account_move_tier_validation/readme/USAGE.md
  account_move_tier_validation/static/description/icon.png
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/views/account_move_view.xml
Labels: 17.0.project_te_576.t148475

#1254 [t148475] Merging open migration PR for: account_move_tier_validation
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/ca.po
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/es_PA.po
  account_move_tier_validation/i18n/sv.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/pyproject.toml
  account_move_tier_validation/readme/CONFIGURE.md
  account_move_tier_validation/readme/CONTRIBUTORS.md
  account_move_tier_validation/readme/DESCRIPTION.md
  account_move_tier_validation/readme/INSTALL.md
  account_move_tier_validation/readme/USAGE.md
  account_move_tier_validation/static/description/icon.png
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/views/account_move_view.xml
Labels: 17.0.project_te_576

#1255 Syncing from upstream OCA/account-invoicing (16.0)
  account_invoice_discount_display_amount/i18n/it.po
  account_tax_one_vat_purchase/i18n/it.po
Labels: 16.0

#1256 Syncing from upstream OCA/account-invoicing (17.0)
  account_invoice_refund_link/i18n/sv.po
Labels: 17.0

#1257 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_move_auto_post_ref/README.rst
  account_move_auto_post_ref/__init__.py
  account_move_auto_post_ref/__manifest__.py
  account_move_auto_post_ref/i18n/account_move_auto_post_ref.pot
  account_move_auto_post_ref/i18n/it.po
  account_move_auto_post_ref/models/__init__.py
  account_move_auto_post_ref/models/account_move.py
  account_move_auto_post_ref/readme/CONTRIBUTORS.md
  account_move_auto_post_ref/readme/DESCRIPTION.md
  account_move_auto_post_ref/readme/USAGE.md
  account_move_auto_post_ref/static/description/icon.png
  account_move_auto_post_ref/static/description/index.html
  account_move_auto_post_ref/tests/__init__.py
  account_move_auto_post_ref/tests/test_invoice.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_auto_post_ref/odoo/addons/account_move_auto_post_ref
  setup/account_move_auto_post_ref/setup.py
Labels: 16.0

#1258 Syncing from upstream OCA/account-invoicing (12.0)
  purchase_stock_picking_return_invoicing/i18n/it.po
Labels: 12.0

#1259 Syncing from upstream OCA/account-invoicing (14.0)
  purchase_stock_picking_return_invoicing/i18n/it.po
Labels: 14.0

#1260 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_show_currency_rate/README.rst
  account_invoice_show_currency_rate/__manifest__.py
  account_invoice_show_currency_rate/i18n/account_invoice_show_currency_rate.pot
  account_invoice_show_currency_rate/i18n/es.po
  account_invoice_show_currency_rate/i18n/it.po
  account_invoice_show_currency_rate/static/description/index.html
  account_invoice_show_currency_rate/views/account_move_view.xml
Labels: 16.0

#1261 Syncing from upstream OCA/account-invoicing (16.0)
  account_invoice_show_currency_rate/i18n/it.po
  account_move_auto_post_ref/i18n/it.po
Labels: 16.0

#1262 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_change_currency/i18n/hr.po
  account_invoice_check_total/i18n/hr.po
  account_invoice_default_code_column/i18n/hr.po
  account_invoice_discount_display_amount/i18n/hr.po
  account_invoice_force_number/i18n/hr.po
  account_invoice_pricelist/i18n/hr.po
  account_invoice_pricelist_sale/i18n/hr.po
  account_invoice_refund_reason_skip_anglo_saxon/README.rst
  account_invoice_refund_reason_skip_anglo_saxon/__init__.py
  account_invoice_refund_reason_skip_anglo_saxon/__manifest__.py
  account_invoice_refund_reason_skip_anglo_saxon/i18n/account_invoice_refund_reason_skip_anglo_saxon.pot
  account_invoice_refund_reason_skip_anglo_saxon/i18n/it.po
  account_invoice_refund_reason_skip_anglo_saxon/models/__init__.py
  account_invoice_refund_reason_skip_anglo_saxon/models/account_invoice_refund_reason.py
  account_invoice_refund_reason_skip_anglo_saxon/models/account_move.py
  account_invoice_refund_reason_skip_anglo_saxon/readme/CONFIGURE.rst
  account_invoice_refund_reason_skip_anglo_saxon/readme/CONTRIBUTORS.rst
  account_invoice_refund_reason_skip_anglo_saxon/readme/DESCRIPTION.rst
  account_invoice_refund_reason_skip_anglo_saxon/static/description/icon.png
  account_invoice_refund_reason_skip_anglo_saxon/static/description/index.html
  account_invoice_refund_reason_skip_anglo_saxon/tests/__init__.py
  account_invoice_refund_reason_skip_anglo_saxon/tests/test_account_invoice_refund_reason_skip_anglo_saxon.py
  account_invoice_refund_reason_skip_anglo_saxon/views/account_invoice_refund_reason_view.xml
  account_invoice_supplier_ref_unique/i18n/hr.po
  account_invoice_supplierinfo_update_discount/i18n/hr.po
  account_invoice_tree_currency/i18n/hr.po
  account_move_tier_validation/i18n/hr.po
  account_receipt_journal/i18n/hr.po
  partner_invoicing_mode_monthly/i18n/hr.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_refund_reason_skip_anglo_saxon/odoo/addons/account_invoice_refund_reason_skip_anglo_saxon
  setup/account_invoice_refund_reason_skip_anglo_saxon/setup.py
  stock_picking_invoicing/i18n/hr.po
Labels: 16.0

#1264 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_global_discount/README.rst
  account_global_discount/__manifest__.py
  account_global_discount/models/account_move.py
  account_global_discount/static/description/index.html
Labels: 16.0

#1265 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_refund_reason_skip_anglo_saxon/i18n/it.po
  account_mail_autosubscribe/README.rst
  account_mail_autosubscribe/__manifest__.py
  account_mail_autosubscribe/static/description/index.html
Labels: 16.0

#1266 Syncing from upstream OCA/account-invoicing (14.0)
  account_invoice_refund_link/i18n/it.po
  sale_line_refund_to_invoice_qty/i18n/it.po
Labels: 14.0

#1267 Syncing from upstream OCA/account-invoicing (16.0)
  account_invoice_refund_link/i18n/it.po
Labels: 16.0

#1268 Syncing from upstream OCA/account-invoicing (17.0)
  account_invoice_refund_link/i18n/it.po
Labels: 17.0

#1269 Syncing from upstream OCA/account-invoicing (14.0)
  sale_line_refund_to_invoice_qty/i18n/it.po
Labels: 14.0

#1270 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_fiscal_position_update/i18n/tr.po
  partner_invoicing_mode_at_shipping/README.rst
  partner_invoicing_mode_at_shipping/__init__.py
  partner_invoicing_mode_at_shipping/__manifest__.py
  partner_invoicing_mode_at_shipping/hooks.py
  partner_invoicing_mode_at_shipping/i18n/es.po
  partner_invoicing_mode_at_shipping/i18n/it.po
  partner_invoicing_mode_at_shipping/i18n/partner_invoicing_mode_at_shipping.pot
  partner_invoicing_mode_at_shipping/migrations/16.0.1.1.0/pre-migrate.py
  partner_invoicing_mode_at_shipping/models/__init__.py
  partner_invoicing_mode_at_shipping/models/res_partner.py
  partner_invoicing_mode_at_shipping/models/sale_order.py
  partner_invoicing_mode_at_shipping/models/stock_picking.py
  partner_invoicing_mode_at_shipping/readme/DESCRIPTION.rst
  partner_invoicing_mode_at_shipping/static/description/index.html
  partner_invoicing_mode_at_shipping/tests/__init__.py
  partner_invoicing_mode_at_shipping/tests/common.py
  partner_invoicing_mode_at_shipping/tests/test_invoice_mode_at_shipping.py
  partner_invoicing_mode_at_shipping/tests/test_invoice_mode_group_delivery.py
  partner_invoicing_mode_at_shipping/views/res_partner.xml
Labels: 16.0

#1271 [BACK] Backmerge
  account_invoice_refund_link/i18n/it.po
  account_invoice_refund_link/i18n/sv.po
Labels: 17.0.project_te_576

#1272 Syncing from upstream OCA/account-invoicing (16.0)
  README.md
  account_invoice_currency_taxes/README.rst
  account_invoice_currency_taxes/__manifest__.py
  account_invoice_currency_taxes/models/account_tax.py
  account_invoice_currency_taxes/static/description/index.html
Labels: 16.0

#1273 Syncing from upstream OCA/account-invoicing (16.0)
  partner_invoicing_mode_at_shipping/i18n/es.po
Labels: 16.0
